services:
  backend:
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    build:
      context: .
      dockerfile: ./production/Dockerfile
    env_file: .env
    environment:
      HOST: 0.0.0.0
      PORT: 80
    ports:
      - 7878:80
  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    image: postgres
    ports:
      - 5431:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "nest"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.12.1
    ulimits:
      memlock: -1
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

volumes:
  pgdata:

  redis_data:
