services:
  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres
    ports:
      - 5431:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.12.1
    ulimits:
      memlock: -1
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

  minio:
    image: "bitnami/minio:latest"
    ports:
      - 9010:9000
      - 9020:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_BUCKET}
      MINIO_SKIP_CLIENT: yes

volumes:
  pgdata:

  redis_data:
