//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub parent_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::category_product::Entity")]
    CategoryProduct,
}

impl Related<super::category_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CategoryProduct.def()
    }
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        super::category_product::Relation::Product.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::category_product::Relation::Category.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
