//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod admin;
pub mod category;
pub mod category_product;
pub mod field;
pub mod field_product;
pub mod file;
pub mod order;
pub mod product;
pub mod products_in_order;
pub mod sea_orm_active_enums;
pub mod service;
