//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

pub use super::admin::Entity as Admin;
pub use super::field::Entity as Field;
pub use super::product::Entity as Product;
pub use super::service::Entity as Service;
