//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "field_type")]
pub enum FieldType {
    #[sea_orm(string_value = "integer")]
    Integer,
    #[sea_orm(string_value = "string")]
    String,
}
